### ISSUE TITLE
"cy:open": "CYPRESS_REMOTE_DEBUGGING_PORT=9222 cypress open" doesn't work

### ISSUE THREAD

**Issue by b7011343** [CraftAcademyLabs/cypress-metamask#16]
When running the tests using the following command I am getting an error:
`"cy:open": "CYPRESS_REMOTE_DEBUGGING_PORT=9222 cypress open"`
Error:
`'CYPRESS_REMOTE_DEBUGGING_PORT' is not recognized as an internal or external command, operable program or batch file.`

I am unsure how to fix this.

**Comment by saxenashivang** [comment]
You can check - https://github.com/saxenashivang/cypress-metamask-v2, I've fixed the known issue and updated it according to the latest cypress.
